# Generated by Django 2.1.5 on 2019-01-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pin',
            field=models.ManyToManyField(null=True, to='core.Pin'),
        ),
    ]
