# Generated by Django 2.1.5 on 2019-01-13 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pin_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='dish',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='pin',
            field=models.ManyToManyField(to='core.Pin'),
        ),
    ]
