# Generated by Django 2.1.5 on 2019-01-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190113_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pin',
            field=models.ManyToManyField(blank=True, to='core.Pin'),
        ),
    ]
