# Generated by Django 2.1.5 on 2019-01-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='location',
        ),
        migrations.AddField(
            model_name='pin',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
